name: Build and Push Don't Starve Admin Go Docker Image
on:
  push

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (docker compose)
        env:
          NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
        run: docker compose build

      - name: Push (docker compose)
        env:
          NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
        run: docker compose push

      - name: Log in to Aliyun ACR
        uses: aliyun/acr-login@v1
        with:
          region-id: ${{ secrets.ALIYUN_REGION_ID }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Tag and Push to Aliyun ACR
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REGISTRY: registry.${{ secrets.ALIYUN_REGION_ID }}.aliyuncs.com/
          NAMESPACE: ${{ secrets.ALIYUN_USERNAME }}
          IMAGE_NAME: dst-admin-go
          TAG: 1.5.1
        run: |
          docker tag ${DOCKER_USERNAME}/${IMAGE_NAME}:${TAG} ${REGISTRY}${NAMESPACE}/${IMAGE_NAME}:${TAG}
          docker push ${REGISTRY}${NAMESPACE}/${IMAGE_NAME}:${TAG}