name: Build and Push Don't Starve Admin Go Docker Image
on:
  push

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.ALIYUN_REGISTRY }}
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build (docker compose)
        env:
          REGISTRY: registry.${{ secrets.ALIYUN_REGION_ID }}.aliyuncs.com
          NAMESPACE: ${{ secrets.ALIYUN_USERNAME }}
          IMAGE_NAME: dst-admin-go
        run: docker compose build

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          region-id: ${{ secrets.ALIYUN_REGION_ID }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Push (docker compose)
        env:
          REGISTRY: registry.${{ secrets.ALIYUN_REGION_ID }}.aliyuncs.com
          NAMESPACE: ${{ secrets.ALIYUN_USERNAME }}
          IMAGE_NAME: dst-admin-go
        run: docker compose push